apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap 
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink }} 
  drinkquote: {{ quote .Values.favorite.drink }} 
  drinkupperquote: {{ .Values.favorite.drink | upper | quote }} 
  {{ if eq .Values.favorite.drink "coffee" }} 
    mug: "true" 
  {{ end }} 
